options:
  sabuser:
    type: string
    default: "sabuser"
    description: "The user to install sabnzbd under"
  port:
    type: int
    default: 8080
    description: "Port for binding sab daemon"
  restore-config:
    type: boolean
    default: False
    description: "Restore a previous configuration from resource"
  proxy-port:
    type: int
    default: 443
    description: "Port to request for reverse proxy access"
  proxy-domain:
    type: string
    default: "sabnzbd"
    description: "Subdomain to request from reverse proxy"
  proxy-url:
    type: string
    default: "/sabnzbd"
    description: 'Urlbase for revrse proxy, must start with a "/"'

