options:
  sabuser:
    type: string
    default: "sabuser"
    description: "The user to install sabnzbd under"
  port:
    type: int
    default: 8080
    description: "Port for binding sab daemon"
  restore-config:
    type: boolean
    default: False
    description: "Restore a previous configuration from resource"
